name: onyxtube
description: HANNUTV Flutter Movie & Series Application
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  url_launcher: ^6.3.0
  http: ^1.2.2
  webview_flutter: ^4.7.0
  webview_flutter_android: ^3.16.2  # <--- YEH NAYA ADD KIYA HAI AUDIO FIX KE LIYE

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/logo.png