name: onyxtube
description: HANNUTV Flutter Movie and Series Application
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  url_launcher: ^6.3.0
  http: ^1.2.2
  webview_flutter: ^4.10.0
  webview_flutter_android: ^4.7.0
  firebase_core: ^4.15.0
  firebase_messaging: ^16.7.0
  firebase_remote_config: ^6.7.0
  # 🔥 Naye Deep Logic Packages Added Below 🔥
  firebase_auth: ^6.7.0
  google_sign_in: ^7.2.0
  cloud_firestore: ^6.10.0
  firebase_database: ^12.6.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/logo.png